model = "gpt-5.4"
model_reasoning_effort = "xhigh"
personality = "pragmatic"
plan_mode_reasoning_effort = "xhigh"
service_tier = "fast"

[notice]
hide_gpt5_1_migration_prompt = true
hide_rate_limit_model_nudge = true

[notice.model_migrations]
"gpt-5.1-codex" = "gpt-5.2-codex"
"gpt-5.3-codex" = "gpt-5.4"

[features]
multi_agent = true
